---
title: "Project 2"
author: "Tom Jeon"
date: "September 13, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Spanish Translation A/B Test
### Goal

A/B tests play a huge role in website optimization. Analyzing A/B tests data is a very important
data scientist responsibility. More specifically, data scientists have to make sure that results are reliable, trustworthy, and conclusions can be drawn.

Furthermore, companies often run tens, if not hundreds, of A/B tests at the same time. Manually
analyzing all of them would require lot of time and people. Therefore, it is common practice to
look at the typical A/B test analysis steps and try to automate as much as possible. This frees
up time for the data scientists to work on more high level topics.

In this project, you will have to analyze results from an A/B test. You will practice using a simple two-table relational database. The ultimate goal would be to design an algorithm to automate some steps.

### Challenge

Company XYZ is a worldwide e-commerce site with localized versions of the site.

A data scientist at XYZ noticed that Spain-based users have a much higher conversion rate than any other Spanish-speaking country. She therefore went and talked to the international team in charge of Spain and Latin America to see if they had any ideas about why that was happening.

Spain and Latin American country managers suggested that one reason could be translation. All Spanish speaking countries had the same translation of the site which was written by a Spaniard. They agreed to try a test where each country would have its one translation written by a local. That is, Argentinian users would see a translation written by an Argentinian, Mexican users by a Mexican and so on. Obviously, nothing would change for users from Spain.

After they ran the test however, they are really surprised to see the test is negative. I.e., it appears that the non-localized translation was doing better!

Your task:

- Confirm that the test is actually negative. That is, it appears that the old version of the site with just one translation across Spain and LatAm performs better.
- Explain why that might be happening. Are the localized translations really worse?
- If you identified what was wrong, design an algorithm that would return `FALSE` if the same problem is happening in the future and `TRUE` if everything is good and the results can be trusted.

### Data

There are two tables: `test_table.csv` and `user_table.csv`.

#### test_table.csv - general info about test results

- **user_id**: the unique id of the user. Can be joined to user id in the other table. For each user, we just check whether conversion happens the first time they land on the site since the test started.
- **date**: when they came to the site for the first time since the test started.
- **source**: marketing channel. Seen this before in Project 1. Ads, SEO, Direct
- **device**: device used by user. Either mobile or web.
- **browser_language**: in browser or app settings, the language chosen by the user. It can be EN, ES, or Other (Other means any language that's not English and Spanish)
- **ads_channel**: if marketing channel is ads, this is the site where the ad was displayed. It
can be: Google, Facebook, Bing, Yahoo ,Other. If the user didn't come via an ad, this field is NA
- **browser**: user browser. It can be: `IE`, `Chrome`, `Android_App`, `FireFox`, `Iphone_App`,
`Safari`, `Opera`
- **conversion**: whether the user converted (1) or not (0). This is our label. A test is considered successful if it increases the proportion of users who convert.
- **test**: users are randomly split into test (1) and control (0). Test users see the new
translation and control the old one. For Spain-based users, this is obviously always 0
since there is no change there.

#### user_table - some info about the user

- **user_id**: the unique id of the users. It can be joined to user id in the other table.
- **sex**: Male or Female
- **age**: user age 
- **country**: user country based on ip address
