---
title: "Project 1"
author: "Tom Jeon"
date: "September 10, 2016"
output:
  html_document: default
  pdf_document:
    latex_engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Conversion Rate
### Goal

Optimizing conversion rate is one of the most common work of a data scientist. The hype of data science has a lot to do with the fact that now we are able to collect all sorts of data about people who buy something on our site as well as people who don't. This gives us a
tremendous opportunity to understand what's working well (and potentially scale it even further)
and what's not working well (and fix it).

The goal of this project is to build a model that predicts conversion rate and, based on the
model, come up with ideas to improve rev􀁝enue.

There are no dates, no tables to join, no feature engineering required, and the problem is pretty straightforward. I think this is a great starting point to get familiar with data science problems.

### Challenge

We have data about users who use this site: whether they converted or not as well as some of their characteristics such as their country, the marketing channel, their age, whether they are repeat users and the number of pages visited during their session (as a proxy for site activity/time spent on site).

Your task is to:

    - Predict conversion rate.
    - Come up with recommendations for the product team and the marketing team to improve conversion rate.

### Data

The data is a CSV file called `conversion_data.csv`. It's included in the `Proj_1` directory on the [ugrid repo](https://github.com/tommyjee/ugrid) and it includes information about signed-in users during one session. Each row is a user session.

The columns:

* _country_: User country based on IP address
* _age_: User age, self-reported at sign-in
* *new_user*: Whether the user created the account during this session or already had an account
* _source_: Marketing channel source
    + Ads: Came to site through advertisement elsewhere
    + Seo: Came to site through search results
    + Direct: Came to site through typing URL on browser
* *total_pages_visited*: number of total pages visited during the session. This is a proxy for time spent on site and engagement during the session
* _converted_: Our response variable.
    + 1 means they converted
    + 0 means they left the site without buying anything
    + Company's goal is to increase conversion rate: \frac{# of conversions}{total sessions}
